# Site settings
title: 涤生的博客
author: 涤生 
description: Disheng
rss_url:
git_url: https://github.com/BrightJasmine

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Shanghai
excerpt_separator:  '<!-- more -->'
gems: [jekyll-paginate]

permalink: /:year/:month/:day/:title.html
paginate: 5

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
